export const images = {
  hero: {
    main: '/images/hero/hero-bg.jpg',
    alt: '/images/hero/hero-bg-alt.jpg',
  },
  services: {
    freight: '/images/services/freight.jpg',
    express: '/images/services/express.jpg',
    warehousing: '/images/services/warehousing.jpg',
    international: '/images/services/international.jpg',
    heavyHaul: '/images/services/heavy-haul.jpg',
    logistics: '/images/services/logistics.jpg',
    courier: '/images/services/courier.jpg',
    longHaulNight: '/images/services/Long Haul transport.jpg',
  },
  fleet: {
    van: [
      '/images/fleet/van.jpg',
      '/images/fleet/van 2.jpg',
      '/images/fleet/van 3.jpg',
      '/images/fleet/van-1.jpg',
      '/images/fleet/van-2.jpg',
      '/images/fleet/van-3.jpg',
      '/images/fleet/van-4.jpg',
      '/images/fleet/van-5.jpg',
    ],
    truck: [
      '/images/fleet/Truck 1.jpg',
      '/images/fleet/Truck 2.jpg',
      '/images/fleet/Truck 3.jpg',
      '/images/fleet/Truck 4.jpg',
      '/images/fleet/Truck 5.jpg',
      '/images/fleet/Truck 6.jpg',
      '/images/fleet/Truck 7.jpg',
      '/images/fleet/Truck 8.jpg',
      '/images/fleet/Truck 9.jpg',
      '/images/fleet/Truck 10.jpg',
      '/images/fleet/Truck 12.jpg',
      '/images/fleet/Truck 13.jpg',
      '/images/fleet/Truck 14.jpg',
      '/images/fleet/Truck 15.jpg',
      '/images/fleet/Truck 16.jpg',
      '/images/fleet/Truck 17.jpg',
      '/images/fleet/Truck 18.jpg',
      '/images/fleet/Truck 19.jpg',
      '/images/fleet/Truck 20.jpg',
      '/images/fleet/Truck 21.jpg',
      '/images/fleet/Truck 22.jpg',
      '/images/fleet/Truck 23.jpg',
      '/images/fleet/Truck 24.jpg',
      '/images/fleet/Truck 25.jpg',
      '/images/fleet/Truck 26.jpg',
      '/images/fleet/Truck 27.jpg',
      '/images/fleet/Scania 1.jpg',
      '/images/fleet/SCANIA.jpg',
      '/images/fleet/VOLVO.jpg',
      '/images/fleet/Mercedez Altros.jpg',
      '/images/fleet/IVECO.jpg',
      '/images/fleet/Iveco (2).jpg',
      '/images/fleet/Iveco T-Way.jpg',
      '/images/fleet/FAW truck (2).jpg',
      '/images/fleet/Faw truck (3).jpg',
      '/images/fleet/Faw Truck.jpg',
      '/images/fleet/FAW 380 6X4 Tipper for Sale in Zambia.jpg',
      '/images/fleet/HOWO 380 CV camion benne 6x4 - Camion HOWO.jpg',
      '/images/fleet/2014 Mitsubishi Fuso Canter TKG-FEB80.jpg',
      '/images/fleet/2020 Scania P360 kamyon.jpg',
      '/images/fleet/781656079076777665.jpg',
      '/images/fleet/truck.jpg',
      '/images/fleet/truck-1.jpg',
      '/images/fleet/truck-2.jpg',
      '/images/fleet/truck-3.jpg',
      '/images/fleet/truck-4.jpg',
      '/images/fleet/truck-5.jpg',
    ],
    trailer: [
      '/images/fleet/Trailer.jpg',
      '/images/fleet/Trailer (2).jpg',
      '/images/fleet/closed trailers.jpg',
      '/images/fleet/Curtainsider Trailers.jpg',
      '/images/fleet/Interlink Trailer.jpg',
      '/images/fleet/Semi-trailers for Sale - New & Used Semi-trailers for Sale.jpg',
      '/images/fleet/SCANIA TRAILER.jpg',
      '/images/fleet/trailer Covers.jpg',
      '/images/fleet/trailer-1.jpg',
      '/images/fleet/trailer-2.jpg',
      '/images/fleet/trailer-3.jpg',
      '/images/fleet/trailer-4.jpg',
      '/images/fleet/trailer-5.jpg',
      '/images/fleet/3 Axle Curtain Side Trailer for Sale In Panama.jpg',
      '/images/fleet/3 Axle Van box Trailer.jpg',
      '/images/fleet/China Curtain Side Trailer For Sale  - ZW Vehicle Group.jpg',
      '/images/fleet/Curtain Side Semi Trailer 90m3 60t 3 Axles blue For Sale - ZW Vehicle Group.jpg',
      '/images/fleet/Curtain Side Trailer for Sale in Equatorial Guinea.jpg',
      '/images/fleet/Dump Trailers.jpg',
      '/images/fleet/enclosed trailer (2).jpg',
      '/images/fleet/enclosed Trailer.jpg',
      '/images/fleet/Enclosed.jpg',
      '/images/fleet/rollerbed box trailer.jpg',
      '/images/fleet/Wilson Conestoga Trailer Guide.jpg',
    ],
    flatbed: [
      '/images/fleet/flatbed.jpg',
      '/images/fleet/flatbed-1.jpg',
      '/images/fleet/flatbed-2.jpg',
      '/images/fleet/flatbed-3.jpg',
      '/images/fleet/flatbed-4.jpg',
      '/images/fleet/flatbed-5.jpg',
      '/images/fleet/40Ft Semi Truck Flatbed Trailer.jpg',
      "/images/fleet/53' Flatbed straight deck.jpg",
      '/images/fleet/Container flat semi-trailer.jpg',
      '/images/fleet/short flatbedded.jpg',
      '/images/fleet/STEEL COIL.jpg',
      '/images/fleet/Plataforma para remolque trailer en venta.jpg',
      '/images/fleet/Flatbed Trailers For Sale _ MyLittleSalesman_com.jpg',
      '/images/fleet/Flatbed Truck Lumber stock photo_ Image of cargo, interstate - 79874624.jpg',
      '/images/fleet/3 Axle 40 Feet Semi Truck Flatbed Trailer for Sale.jpg',
      '/images/fleet/3 Axle 40Ft Flatbed Semi for Sale in Ghana.jpg',
      '/images/fleet/60 Ton Low Flatbed Semi Trailer 40_45 Feet for Sale in Congo.jpg',
    ],
    refrigerated: [
      '/images/fleet/Refrigerated Truck.jpg',
      '/images/fleet/refrigerated trailer.jpg',
      '/images/fleet/refrigerated trailer (2).jpg',
      '/images/fleet/refrigerator trailers.jpg',
      '/images/fleet/refrigerator trailers (2).jpg',
      '/images/fleet/refrigerator trailers (3).jpg',
      '/images/fleet/refrigirated Truck 1.jpg',
      '/images/fleet/Trailer Extend Hot refrigeration.jpg',
      '/images/fleet/Transport Refrigeration Units for Refrigerated Truck_Van_Trailers.jpg',
      '/images/fleet/Getting To Know Your Refrigeration Trailer _ 2026.jpg',
      '/images/fleet/Refrigerated Trailers For Sale _ MyLittleSalesman_com.jpg',
      '/images/fleet/refrigerated.jpg',
      '/images/fleet/refrigerated-1.jpg',
      '/images/fleet/refrigerated-2.jpg',
      '/images/fleet/refrigerated-3.jpg',
      '/images/fleet/refrigerated-4.jpg',
      '/images/fleet/refrigerated-5.jpg',
    ],
    heavy: [
      '/images/fleet/heavy haul.jpg',
      '/images/fleet/heavy haul scania.jpg',
      '/images/fleet/heavy haul volvo.jpg',
      '/images/fleet/Haul trucks.jpg',
      '/images/fleet/HOWO 380 CV camion benne 6x4 - Camion HOWO.jpg',
      '/images/fleet/FAW 380 6X4 Tipper for Sale in Zambia.jpg',
      '/images/fleet/heavy.jpg',
      '/images/fleet/heavy-1.jpg',
      '/images/fleet/heavy-2.jpg',
      '/images/fleet/heavy-3.jpg',
      '/images/fleet/heavy-4.jpg',
      '/images/fleet/heavy-5.jpg',
    ],
  },
  about: {
    team: '/images/about/team.jpg',
    facility: '/images/about/facility.jpg',
    teamMembers: {
      jamesMwangi: '/images/about/James Mwangi.jpg',
      sarahKimani: '/images/about/Sarah Kimani.jpg',
      davidOchieng: '/images/about/David Ochieng.jpg',
      graceWanjiku: '/images/about/Grace Wanjiku.jpg',
      peterKamau: '/images/about/peter kamau.jpg',
      aliceNjeri: '/images/about/alice.jpg',
    },
  },
  gallery: {
    items: [
      '/images/gallery/gallery-1.jpg',
      '/images/gallery/gallery-2.jpg',
      '/images/gallery/gallery-3.jpg',
      '/images/gallery/gallery-4.jpg',
      '/images/gallery/gallery-5.jpg',
      '/images/gallery/gallery-6.jpg',
    ],
  },
  blog: {
    coverDefault: '/images/blog/cover-default.jpg',
  },
  testimonials: {
    avatars: [
      '/images/testimonials/avatar-1.jpg',
      '/images/testimonials/avatar-2.jpg',
      '/images/testimonials/avatar-3.jpg',
    ],
  },
  cta: {
    background: '/images/cta/cta-bg.jpg',
  },
  contact: {
    office: '/images/contact/office.jpg',
  },
} as const;
